In [15]:
import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])

A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
import numpy as np

B = np.array([[5,-4,3,7],[3,6,5,-4],[-4,-3,0,5],[4,8,4,-2]])

B[0,0], B[0,1], B[1,0], B[1,1], B[2,2]


(5, -4, 3, 6, 0)

In [22]:
import numpy as np

B = np.array([[5,-4,3,7],[3,6,5,-4],[-4,-3,0,5],[4,8,4,-2]])

B[:4,1]

array([-4,  6, -3,  8])

In [23]:
import numpy as np

B = np.array([[5,-4,3,7],[3,6,5,-4],[-4,-3,0,5],[4,8,4,-2]])

B[2,:4]

array([-4, -3,  0,  5])

In [44]:
import numpy as np

R = np.eye(4)
B = np.array([[5,-4,3,7],[3,6,5,-4],[-4,-3,0,5],[4,8,4,-2]])

for n in range(4):
    R[n,n] = B[n,n]

R

array([[ 5.,  0.,  0.,  0.],
       [ 0.,  6.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -2.]])