In [51]:
#1
import numpy as np

A = np.array([[3,6,0,7]])

B = np.array([[7,13,2],[0,6,4]])

C = np.array([[4,1,-2],[-4,9,12],[2,15,-6]])

print(np.shape(A), np.shape(B), np.shape(C))

(1, 4) (2, 3) (3, 3)


In [52]:
#2
import numpy as np

print(np.eye(2))
print(np.eye(3))

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [53]:
#3
import numpy as np

A=np.array([[7,5,0,-8],[2,3,-2,9],[9,-5,-6,3]])

print(A[1,3])
print(A[2,:])
print(A[:,3])

9
[ 9 -5 -6  3]
[-8  9  3]


In [54]:
#4
import numpy as np

A = np.array([[4,7,1],[8,5,3],[3,2,4]])
B = np.array([[5,-3,7],[4,5,-4],[3,0,1]])
I=np.eye(3)

print(np.subtract(2*A,I))
print(np.subtract(3*A,2*B))

[[ 7. 14.  2.]
 [16.  9.  6.]
 [ 6.  4.  7.]]
[[  2  27 -11]
 [ 16   5  17]
 [  3   6  10]]


In [55]:
#5
import numpy as np

A = np.array([[1,3,2],[4,5,7]])
B = np.array([[5,-3],[0,2],[4,7]])

print(np.dot(A,B))
print(np.dot(B,A))

[[13 17]
 [48 47]]
[[ -7   0 -11]
 [  8  10  14]
 [ 32  47  57]]


In [56]:
#6
import numpy as np

A = np.array([[0,0,1,0],[0,0,0,1],[-1,0,0,0],[0,-1,0,0]])

print("A의 1승:\n", A)
B = np.dot(A,A)
print("A의 2승:\n", B)
B = np.dot(B,A)
print("A의 3승:\n", B)
B = np.dot(B,A)
print("A의 4승:\n", B)
B = np.dot(B,A)
print("A의 5승:\n", B)

A의 1승:
 [[ 0  0  1  0]
 [ 0  0  0  1]
 [-1  0  0  0]
 [ 0 -1  0  0]]
A의 2승:
 [[-1  0  0  0]
 [ 0 -1  0  0]
 [ 0  0 -1  0]
 [ 0  0  0 -1]]
A의 3승:
 [[ 0  0 -1  0]
 [ 0  0  0 -1]
 [ 1  0  0  0]
 [ 0  1  0  0]]
A의 4승:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
A의 5승:
 [[ 0  0  1  0]
 [ 0  0  0  1]
 [-1  0  0  0]
 [ 0 -1  0  0]]


In [57]:
#7
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[4,3],[2,1]])
At = np.transpose(A)
Bt = np.transpose(B)

print(np.transpose(np.dot(A,B)))
print(np.dot(At,Bt))
print(np.dot(Bt,At))

[[ 8 20]
 [ 5 13]]
[[13  5]
 [20  8]]
[[ 8 20]
 [ 5 13]]


In [58]:
#8
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(np.trace(np.dot(A,B)))
print(np.trace(np.dot(B,A)))

69
69
